STOCKS = [
"RELIANCE.NS","TCS.NS","INFY.NS","HDFCBANK.NS","ICICIBANK.NS",
"SBIN.NS","AXISBANK.NS","KOTAKBANK.NS","LT.NS","HCLTECH.NS",
"ITC.NS","WIPRO.NS","MARUTI.NS","BAJFINANCE.NS","BAJAJFINSV.NS",
"ADANIENT.NS","ADANIPORTS.NS","ONGC.NS","COALINDIA.NS","NTPC.NS",
"POWERGRID.NS","ULTRACEMCO.NS","JSWSTEEL.NS","TATASTEEL.NS",
"HINDALCO.NS","GRASIM.NS","ASIANPAINT.NS","PIDILITIND.NS",
"NESTLEIND.NS","BRITANNIA.NS","TITAN.NS","SUNPHARMA.NS",
"DRREDDY.NS","CIPLA.NS","DIVISLAB.NS","APOLLOHOSP.NS",
"TECHM.NS","LTIM.NS","MPHASIS.NS","PERSISTENT.NS",
"DLF.NS","GODREJPROP.NS","TATAPOWER.NS","EICHERMOT.NS",
"HEROMOTOCO.NS","M&M.NS","BHARTIARTL.NS","INDUSINDBK.NS",
"HDFCLIFE.NS","SBILIFE.NS"
]